### PR TITLE
update patches following recent upstreams 

### PR DESCRIPTION
**Pull request by gabylb**
Please see comments in each commit.

### CODE REVIEW

**Review by netskink — APPROVED** [review]
Looks good to me.  I would like to merge so I can test building it.  Perhaps I should ask how to do a test build with zopen prior.  Perhaps do a git pull based upon the pull request commit.

**Comment by netskink** [comment]
fwiw, @gabylb and @IgorTodorovskiIBM the pull request and build of this pull request.  Did not fail, but did not complete either.  Here is the workflow and end result:

workflow
```
$ git clone git@github.com:ZOSOpenTools/v8port.git v8port.upstream
$ cd v8port.upstream/
$ git pull origin  pull/17/head
$ zopen build  
```

Truncated final output
```
:DEBUG:: 'Processing dir: patches/src/heap/base'
:DEBUG:: 'Processing dir: patches/src/heap'
:DEBUG:: 'Processing dir: patches/src/base/platform'
:DEBUG:: 'Processing dir: patches/src/base/debug'
:DEBUG:: 'Processing dir: patches/src/base'
:DEBUG:: 'Processing dir: patches/src'
:DEBUG:: 'Processing dir: patches/buildtools/zos'
:DEBUG:: 'Processing dir: patches/buildtools'
:DEBUG:: 'Processing dir: patches'
:DEBUG:: 'Processing dir: log'
:DEBUG:: 'Processing dir: install'
:DEBUG:: 'Processing dir: .'
:DEBUG:: 'Moving unpaxed processing-directory back to main rootfs store.'
:DEBUG:: 'Merge symlinks into main filesystem using tmp tar file v8.usr.tar'
:DEBUG:: 'Generating intermediary tar file'
:DEBUG:: 'Generating listing for remove processing (including main symlink).'
:DEBUG:: 'Extracting tar to rootfs.'
:DEBUG:: 'Cleaning temp resources.'
:DEBUG:: 'Switching to previous cwd - current work dir was purged.'
- Integration complete.
- Sourcing environment to run any setup
Setting up v8...
append_to_setup()
Setup completed.
zopen-build completed in 1356 seconds.
xxxxx@xxx v8port.upstream (main)
$ ls v8base/v8/
AUTHORS                           LICENSE.strongtalk                codereview.settings
BUILD.bazel                       LICENSE.v8                        custom_deps
BUILD.gn                          LOONG_OWNERS                      docs
CEEDUMP.20240724.144125.50529767  MIPS_OWNERS                       gn
CEEDUMP.20240724.144210.199003    OWNERS                            gni
CODE_OF_CONDUCT.md                PPC_OWNERS                        include
COMMON_OWNERS                     PRESUBMIT.py                      infra
DEPS                              README.md                         samples
DIR_METADATA                      RISCV_OWNERS                      src
ENG_REVIEW_OWNERS                 S390_OWNERS                       test
INFRA_OWNERS                      WATCHLISTS                        testing
INTL_OWNERS                       WORKSPACE                         third_party
LICENSE                           bazel                             tools
LICENSE.fdlibm                    build_overrides                   zos
xxxx@xxxx v8port.upstream (main)
```

**Comment by netskink** [comment]
hmm.  Trying to recover manually.

```
cd v8base/v8
$ mkdir out
xxx@xxx v8 (main)
$ mkdir out/zos_s390x.release
$ cat << EOF > out/zos_s390x.release/args.gn
is_debug=false
treat_warnings_as_errors=false
is_component_build=false
EOF
xxx@xxxx v8 (main)
$ gn -v gen out/zos_s390x.release
ERROR at //.gn:5:1: Unable to load "/x/xxxx/zopen/dev/v8port.upstream/v8base/v8/build/dotfile_settings.gni".
import("//build/dotfile_settings.gni")
^------------------------------------
xxxx@xxx v8 (main)

**Comment by gabylb** [comment]
What does `ls -lT build/dotfile_settings.gni` display? In my standalone v8, it's:
```
t ISO8859-1   T=on  -rw-rw-r--   1 x y       1588 May 16 11:23 build/dotfile_settings.gni
```

**Comment by netskink** [comment]
well apparantly, this is not the way to push mods to the pull request.   It merged the code.  I was hoping to preserver the pull request but to show the failures I was having with it.

```
$ git push origin main:zos-port
```

**Pull request merged**
