### PR TITLE
disable download of zos-s390x packages

### PR DESCRIPTION
**Pull request by gabylb**
- disable download of zos-s390x packages not present upstream; those that are required (clang, ninja, gn) are already available on z/OS; others such as reclient and luci-go, are currently not required on z/OS
- force download of the z/OS-supported depot_tools commit so `gclient sync` works on the current (fce38915 from Nov 22 2023) v8port patches, until those patches are updated with a more recent V8 head commit.
- bypass check of clang_revision since llvm-clang for zos-s390x is not in the upstream Google storage, and so is not downloaded

Run the following to update `v8/DEPS` (after `fetch v8` or `git pull`), before running `gclient sync` from under the `v8` directory:
```
$ sed -i -f <path-to>/v8port/patches/DEPS.sed DEPS
```
See https://issues.chromium.org/issues/323790693#comment12 - the last item "update the fetched v8/DEPS".

Example of the `and host_os != "zos"` changes to DEPS made by the above sed:
```
  'buildtools/linux64': {
    'packages': [
      {
        'package': 'gn/gn/linux-${{arch}}',
        'version': Var('gn_version'),
      }
    ],
    'dep_type': 'cipd',
    'condition': 'host_os == "linux" and host_cpu != "s390" and host_os != "zos" and host_cpu != "ppc"',
  },
...
  {
    # Note: On Win, this should run after win_toolchain, as it may use it.
    'name': 'clang',
    'pattern': '.',
    # clang not supported on aix
    'condition': 'host_os != "aix" and host_os != "zos"',
    'action': ['python3', 'tools/clang/scripts/update.py'],
  },
...
   'third_party/depot_tools':
-    Var('chromium_url') + '/chromium/tools/depot_tools.git' + '@' + '38b8de056ebb9d0aa138f09907fa83c5b6107bb5',
+    Var('chromium_url') + '/chromium/tools/depot_tools.git' + '@' + '9d64acedead8bf69b1eee2645a18f8fd47a1100d',
...
```

### CODE REVIEW

**Comment by IgorTodorovskiIBM** [comment]
Many of the z/OS CI instances are down, looking into it.

**Review by IgorTodorovskiIBM — APPROVED** [review]
LGTM

**Review by netskink — APPROVED** [review]
Thank you Gaby!  This is excellent news!

**Pull request merged**
